server:
  port: 8080

spring:
  application:
    name: springboot-transaction-multiple-datasource
  profiles:
    active: only-oracle

logging:
  level:
     org:
      springframework:
        '[orm.jpa]': TRACE
        '[transaction]': TRACE