-- create proc
CREATE OR REPLACE PROCEDURE user_nhan.create_car_table_proc (
    in_schema IN dba_tables.owner%TYPE,
    in_table_name IN dba_tables.table_name%TYPE,
    out_msg OUT VARCHAR2)
AS
    tbl_count number;
    sql_stmt long;
    insert_sql_stmt long;

BEGIN
    SELECT COUNT(1) INTO tbl_count
    FROM dba_tables
    WHERE UPPER(owner) = UPPER(in_schema)
        AND UPPER(table_name) = UPPER(in_table_name);

    IF (tbl_count = 0)
        THEN
        sql_stmt:='
        CREATE TABLE ' || in_schema || '.' || in_table_name || '(
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            name VARCHAR (255) NOT NULL
        )';
        EXECUTE IMMEDIATE sql_stmt;
        COMMIT;
        out_msg := 'Table was created';

        insert_sql_stmt:='
        INSERT INTO ' || in_schema || '.' || in_table_name || ' (name) VALUES
            (''FORD''),
            (''HONDA''),
            (''HUYNDAI''),
            (''TOYOTA'')';
        EXECUTE IMMEDIATE insert_sql_stmt;
        COMMIT;
        out_msg := out_msg || ' - ' || 'Table was inserted';
    ELSE
        out_msg := 'Table already exists';
    END IF;
END;
/
-- create proc
CREATE OR REPLACE PROCEDURE user_nhan.drop_car_table_proc (
    in_schema IN dba_tables.owner%TYPE,
    in_table_name IN dba_tables.table_name%TYPE)
AS
    tbl_count number;
    sql_stmt long;

BEGIN
    SELECT COUNT(1) INTO tbl_count
    FROM dba_tables
    WHERE UPPER(owner) = UPPER(in_schema)
        AND UPPER(table_name) = UPPER(in_table_name);

    IF (tbl_count > 0)
        THEN
        sql_stmt := 'DROP TABLE ' || in_schema || '.' || in_table_name;
        EXECUTE IMMEDIATE sql_stmt;
        COMMIT;
    END IF;
END;