app:
  datasource:
    vehicle:
      url: jdbc:oracle:thin:@localhost:1521:FREE
      username: user_vehicle
      password: ngocnhan
      driver-class-name: oracle.jdbc.OracleDriver
      jpa:
        properties:
          hibernate:
            '[show_sql]': true
      hikari:
        pool-name: vehicle-pool-name
        maximum-pool-size: 1
        minimum-idle: 1
        schema: user_vehicle

    wild:
      url: jdbc:oracle:thin:@localhost:1521:FREE
      username: user_wild
      password: ngocnhan
      driver-class-name: oracle.jdbc.OracleDriver
      jpa:
        properties:
          hibernate:
            '[show_sql]': true
      hikari:
        pool-name: wild-pool-name
        maximum-pool-size: 1
        minimum-idle: 1
        schema: user_wild