spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: user_nhan
    password: ngocnhan
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      schema: user_nhan
      pool-name: user-nhan-pool-name
      maximum-pool-size: 1
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        '[show_sql]': true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: trace