spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: system
    password: ngocnhan
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      schema: system
      pool-name: system-pool-name
      maximum-pool-size: 1
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        '[show_sql]': true