server:
  port: 8080

spring:
  application:
    name: springboot-transaction-jdbc

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: user_transaction
    password: ngocnhan
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: user_transaction-pool-name
      maximum-pool-size: 10
      minimum-idle: 1
      schema: user_transaction
  jpa:
    properties:
      hibernate:
        '[show_sql]': true

logging:
  level:
     org:
      springframework:
        '[orm.jpa]': TRACE
        '[transaction]': TRACE