:page-module-title: Spring Boot Transaction Multiple DataSource

include::ROOT:partial$header.adoc[]

[IMPORTANT]
.Module {page-module-title}
====
This module *DON'T* show how config multiple transaction properly!
====

=== Demonstration of Example

  ✓ Connect Multiple Database:::
    . Use JPA for saving new object, deleting existed object and finding all object in connected databases
    . Use `ChainedTransactionManager.java` for rollback transaction
    . Use JTA for rollback transaction

.Structure of source
[source]
----
springboot-transaction-multiple-datasource
  +- main
  | +- com.springboot.code.example.transaction.multiple.datasource
  |   +- `MultipleDatasourceApplication.java`
  |   |
  |   +- config
  |   | +- `ChainedTransactionManagerConfig.java`
  |   | +- `JtaTransactionManagerConfig.java`
  |   | +- `VehicleDatasourceConfig.java`
  |   | +- `WildDatasourceConfig.java`
  |   | +- `VehicleJtaDatasourceConfig.java`
  |   | +- `WildJtaDatasourceConfig.java`
  |   |
  |   +- example
  |   | +- `MultipleDatasourceExample.java`
  |   | +- `MultipleDatasourceJtaExample.java`
  |
  +- test
    +- com.springboot.code.example.transaction.multiple.datasource
      +- example
      | +- `MultipleDatasourceExampleTests.java`
      | +- `MultipleDatasourceJtaExampleTests.java`
----

.Run below test file for executing code
* `MultipleDatasourceExampleTests.java`
* `MultipleDatasourceJtaExampleTests.java`

[NOTE]
.Should use JTA instead `ChainedTransactionManager.java`
====

. `MultipleDatasourceExample.getAllWithException` use `@Deprecated ChainedTransactionManager.java`
. `MultipleDatasourceJtaExample.getAllWithException` use JTA


You can run test or create API, queue or batch, etc to test and see result from selecting database
====

=== Reference Guide
. https://dzone.com/articles/most-common-spring-transactional-mistakes[Spring `@Transactional` Mistakes Everyone Makes]
. https://github.com/spring-projects/spring-data-commons/issues/2232[Deprecate ChainedTransactionManager]
. https://www.atomikos.com/Documentation/ConfiguringOracleForXA[Configuring Oracle for XA]
. https://spring.io/blog/2011/08/15/configuring-spring-and-jta-without-full-java-ee/[Configuring Spring and JTA without full Java EE]
. https://www.fabiomaffioletti.me/blog/2014/04/15/distributed-transactions-multiple-databases-spring-boot-spring-data-jpa-atomikos/[Distributed transactions with multiple databases, Spring Boot, Spring Data JPA and Atomikos]
. https://www.atomikos.com/Documentation/SpringIntegration[Spring Integration]
. https://medium.com/@inzuael/how-to-use-multiple-datasources-with-springboot-exposed-jpa-6bd705bfe994[How to use multiple datasources with SpringBoot + Exposed/JPA]