:page-module-title: Spring Boot Transaction Multiple DataSource

include::ROOT:partial$header.adoc[]

[IMPORTANT]
.Module {page-module-title}
====
This module *DON'T* show how config multiple transaction properly!
====

=== Demonstration of Example

  ✓ Connect Multiple Database:::
    . Use JPA for saving new object, deleting existed object and finding all object in connected databases
    . Use `ChainedTransactionManager.java` for rollback transaction
    . Use JTA for rollback transaction

.Structure of source
[source]
----
springboot-transaction-multiple-datasource
  +- main
  | +- com.springboot.code.example.transaction.multiple.datasource
  |   +- `MultipleDatasourceApplication.java`
  |   |
  |   +- config
  |   |  +- `MultipleDatasourceConfig.java` // config transaction
  |   |  +- `VehicleDatasourceConfig.java` // config first database
  |   |  +- `WildDatasourceConfig.java`  // config second database
  |   |
  |   +- example
  |   |  +- `MultipleDatasourceExample.java`
  |   |  +- `MultipleDatasourceJtaExample.java`
  |
  +- test
    +- com.springboot.code.example.transaction.multiple.datasource
      +- example
      |  +- `MultipleDatasourceExampleTests.java`
      |  +- `MultipleDatasourceJtaExampleTests.java`
----

.Run below test file for executing code
* `MultipleDatasourceExampleTests.java`
* `MultipleDatasourceJtaExampleTests.java`

[NOTE]
.Should use JTA instead `ChainedTransactionManager.java`
====

. `MultipleDatasourceExample.getAllWithException` use `@Deprecated ChainedTransactionManager.java`
. `MultipleDatasourceJtaExample.getAllWithException` use JTA


You can run test or create API, queue or batch, etc to test and see result from selecting database
====