CREATE TABLE user_nhan.NAME_PREFIX (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    AGE NUMBER,
    CREATEDATETIME TIMESTAMP DEFAULT SYSDATE
);

BEGIN
    FOR i IN 1 .. 20
    LOOP
        INSERT INTO user_nhan.NAME_PREFIX (FIRST_NAME, LAST_NAME, AGE)
        WITH temp AS
        (
            SELECT dbms_random.string('A', 20), dbms_random.string('L', 20), LEVEL
            FROM DUAL
            CONNECT BY LEVEL <= 1000000
        )
        SELECT *
        FROM temp;
        COMMIT;
    END LOOP;
END;