spring:
  sql:
    init:
      data-locations: 
      - classpath:data-postgre.sql

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ngocnhan
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: vehicle
      pool-name: vehicle-pool-name
      maximum-pool-size: 1
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        '[show_sql]': true

logging:
  level:
    org:
      springframework:
        jdbc: TRACE