CREATE SCHEMA IF NOT EXISTS VEHICLE;

CREATE TABLE IF NOT EXISTS VEHICLE.CAR (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR (255) NOT NULL
);

INSERT INTO VEHICLE.CAR (NAME) VALUES
    ('FORD'),
    ('HONDA'),
    ('HUYNDAI'),
    ('AXE'),
    ('TOYOTA');

CREATE OR REPLACE FUNCTION VEHICLE.COUNT_CAR()
RETURN SMALLINT AS $$
DECLARE count_car SMALLINT;
BEGIN
    SELECT COUNT(1) INTO count_car
    FROM VEHICLE.CAR;

    RETURN count_car;
END;
$$  LANGUAGE plpgsql;