DROP TABLE IF EXISTS ANIMAL;
DROP TABLE IF EXISTS ANIMAL_JTA;

CREATE TABLE ANIMAL (
    id SERIAL PRIMARY KEY,
    NAME VARCHAR (255) NOT NULL
);

INSERT INTO ANIMAL (NAME) VALUES
    ('LION'),
    ('TIGER'),
    ('MOUSE'),
    ('CAT');

CREATE TABLE ANIMAL_JTA (
    id SERIAL PRIMARY KEY,
    NAME VARCHAR (255) NOT NULL
);

INSERT INTO ANIMAL_JTA (NAME) VALUES
    ('LION'),
    ('TIGER'),
    ('MOUSE'),
    ('CAT');