server:
  port: 8080

spring:
  application:
    name: springboot-elastic

  rabbitmq:
    host: localhost
    port: 5672
    username: ngocnhan
    password: ngocnhan
    listener:
      simple:
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3s
          max-interval: 3s

app:
  queue:
    name: local_QUEUE_TEST
    name-listener: local_QUEUE_TEST_LISTENER