ALTER SESSION SET "_oracle_script"=true;

-- drop user
DROP USER user_wild cascade;

-- create user
CREATE USER user_wild IDENTIFIED BY ngocnhan;

-- grant privilege
GRANT SELECT ON sys.dba_tables TO user_wild;
GRANT ALL PRIVILEGES TO user_wild;

CREATE TABLE user_wild.ANIMAL (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NAME VARCHAR (255) NOT NULL
);

INSERT INTO user_wild.ANIMAL (NAME) VALUES
    ('LION'),
    ('TIGER'),
    ('MOUSE'),
    ('CAT');