ALTER SESSION SET "_oracle_script"=true;

-- drop user
DROP USER user_vehicle cascade;

-- create user
CREATE USER user_vehicle IDENTIFIED BY ngocnhan;

-- grant privilege
GRANT SELECT ON sys.dba_tables TO user_vehicle;
GRANT ALL PRIVILEGES TO user_vehicle;

CREATE TABLE user_vehicle.CAR (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NAME VARCHAR (255) NOT NULL
);

INSERT INTO user_vehicle.CAR (NAME) VALUES
    ('FORD'),
    ('HONDA'),
    ('HUYNDAI'),
    ('TOYOTA');