CREATE SCHEMA IF NOT EXISTS VEHICLE;

CREATE TABLE IF NOT EXISTS VEHICLE.CAR (
    ID SMALLINT auto_increment,
    NAME VARCHAR (255) NOT NULL
);

INSERT INTO VEHICLE.CAR (NAME) VALUES
    ('FORD'),
    ('HONDA'),
    ('HUYNDAI'),
    ('TOYOTA');