CREATE SCHEMA IF NOT EXISTS WILD;

CREATE TABLE IF NOT EXISTS WILD.ANIMAL (
    ID SMALLINT auto_increment,
    NAME VARCHAR (255) NOT NULL
);

INSERT INTO WILD.ANIMAL (NAME) VALUES
    ('LION'),
    ('TIGER'),
    ('MOUSE'),
    ('CAT');