:page-module-title: Spring Boot Database Multiple DataSource

include::ROOT:partial$header.adoc[]

[IMPORTANT]
.Module {page-module-title}
====
This module *DON'T* show how config multiple database properly!
====

=== Demonstration of Example

  ✓ Connect Multiple Database:::
    . Use JPA for saving new object, deleting existed object and finding all object in connected databases
    . Use JTA for rollback transaction

.Structure of source
[source]
----
springboot-database-multiple-datasource
  +- main
  | +- com.springboot.code.example.database.multiple.datasource
  |   +- `MultipleDatasourceApplication.java`
  |   |
  |   +- config
  |   |  +- `AtomikosConfiguration.java` // config transaction
  |   |  +- `VehicleDatasourceConfig.java` // config first database
  |   |  +- `WildDatasourceConfig.java`  // config second database
  |   |
  |   +- example
  |   |  +- `MultipleDatasourceExample.java`
  |
  +- test
    +- com.springboot.code.example.database.multiple.datasource
      +- example
      |  +- `MultipleDatasourceExampleTests.java`
----

.Run below test file for executing code
* `MultipleDatasourceExampleTests.java`

[NOTE]
.Why use JTA
====
Flow `MultipleDatasourceExample.java`::
  First Database:::
    . insert record
    . delete record
  Seconde Database:::
    . insert record
    . delete record
  Result:::
    * list data of first database and second database

And I wrote unit test but only first database successful rollback, second database committed. *This is very risk.* So I research... and *result is JTA*, _if you know how to rollback both database without JTA, please teach me._

xref:springboot-transaction:springboot-transaction-multiple-datasource/index.adoc[Check out here for more detail...]
====