:page-module-title: Database

include::ROOT:partial$header.adoc[]

== What module `*{page-module-title}*` have

[pass]
<div class="bd-code-snippet">
  <div class="d-flex align-items-center highlight-toolbar ps-3 pe-2 py-1 border-bottom">
    <strong>Modules</strong>
  </div>
  <div class="highlight">
    spring-boot-code-example <br/>
    └── database
  </div>
</div>
<div class="bd-example-snippet bd-code-snippet bd-file-ref">
    <div class="d-flex align-items-center highlight-toolbar ps-3 pe-2 py-1 border-bottom">
      <strong>Unit test in module</strong>
    </div>
    <div class="highlight">
<pre>
com.springboot.code.example.rabbitmq
├── entitymanager // <strong>test EntityManager</strong>
│   ├── NativeQueryServiceTest.java // <strong>convert Tuple to POJO using <code>EntityManager.createNativeQuery</code></strong>
│   └── TypedQueryPaginationTest.java // <strong>retrieve native query from <code>TypedQuery</code></strong>
├── repository // <strong>test function in example_pack</strong>
│   ├── NamePrefixRepositoryTest.java // <strong>test method in <code>NamePrefixRepository.java</code></strong>
│   ├── testcase
│   │   └── NamePrefixRepositoryTestArguments.java
└── benchmark // <strong>Benchmark for structure TABLE(rows here...)</strong>
    ├── BindingBenmark.java
    └── NameInfoBenmark.java
</pre>
    </div>
</div>

== Reference

* [x] https://stackoverflow.com/questions/31267274/spring-boot-programmatically-setting-profiles[Spring Boot Programmatically setting profiles]
* [x] https://www.oracle.com/technical-resources/articles/java/architect-benchmarking.html[Avoiding Benchmarking Pitfalls on the JVM]
* [x] https://github.com/openjdk/jmh[Java Microbenchmark Harness (JMH)]
* [x] https://blogs.oracle.com/connect/post/on-rownum-and-limiting-results[On ROWNUM and Limiting Results]
* [x] https://dzone.com/articles/jmh-benchmark-rest-apis[JMH: Benchmark REST APIs]
* [x] https://www.baeldung.com/java-exceptions-performance[Performance Effects of Exceptions in Java]
* [x] https://www.logicbig.com/tutorials/java-ee-tutorial/jpa/criteria-api-construct.html[JPA Criteria API - Selecting User defined Objects using CriteriaBuilder#construct()]
* [x] https://stackoverflow.com/questions/11170609/how-to-count-a-group-by-result-with-jpa-and-criteriabuilder[How to count a group by result with JPA and CriteriaBuilder?]
* [x] https://stackoverflow.com/questions/5423937/how-do-i-count-the-number-of-rows-returned-by-subquery/66323540#66323540[How do I count the number of rows returned by subquery?]