server:
  port: 8080

spring:
  application:
    name: springboot-database-jdbc

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: user_nhan
    password: ngocnhan
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: user-nhan-pool-name
      maximum-pool-size: 1
      minimum-idle: 1
      schema: user_nhan
  jpa:
    properties:
      hibernate:
        '[show_sql]': true

logging:
  level:
    '[com.zaxxer.hikari.pool.HikariPool]': DEBUG