CREATE TABLE IF NOT EXISTS Book (
  id SMALLSERIAL PRIMARY KEY, 
  title VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS Book_Author (
  book INTEGER,
  author INTEGER
);

CREATE TABLE IF NOT EXISTS AUTHOR (
  id SMALLSERIAL PRIMARY KEY,
  name VARCHAR(200)
);