server:
  port: 8080

spring:
  application:
    name: springboot-rabbitmq

  rabbitmq:
    host: localhost
    port: 5672
    username: ngocnhan
    password: ngocnhan
    listener:
      simple:
        concurrency: 1
        default-requeue-rejected: false