app:
  datasource:
    vehicle:
      url: jdbc:h2:mem:vehicle
      username: sa
      password:
      driver-class-name: org.h2.Driver
      jpa:
        properties:
          hibernate:
            '[show_sql]': true
            '[default_schema]': vehicle
      configuration:
        pool-name: vehicle-pool-name
        maximum-pool-size: 1
        minimum-idle: 1

    wild:
      url: jdbc:h2:mem:wild
      username: sa
      password:
      driver-class-name: org.h2.Driver
      jpa:
        properties:
          hibernate:
            '[show_sql]': true
            '[default_schema]': wild
      configuration:
        pool-name: wild-pool-name
        maximum-pool-size: 1
        minimum-idle: 1