name: Java CI with Maven

on:
  push:
    branches: [ 'refactor/3.0.x' ]
  pull_request:
    branches: [ '3.0.x' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: JaCoCo Code Coverage Report
      uses: PavanMudigonda/jacoco-reporter@v4.9
      with:
        coverage_results_path: 'target/site/jacoco/jacoco.xml'
        coverage_report_title: 'Test coverage results'
        coverage_report_name: 'Test coverage results'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 80
    - name: Upload Code Coverage Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report-markdown
        path: '*/coverage-results.md'
        retention-days: 1  